# Generated by Django 3.2.6 on 2021-08-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggers', '0002_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='data',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
