# Generated by Django 3.2.6 on 2021-08-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggers', '0003_alter_dog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='data',
            field=models.FloatField(null=True),
        ),
    ]
