# Generated by Django 3.2.6 on 2021-08-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('credit_hours', models.IntegerField()),
            ],
        ),
    ]
