# Generated by Django 3.2.6 on 2021-08-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='person',
            field=models.ManyToManyField(to='polls.Person'),
        ),
    ]
