# Generated by Django 3.2.6 on 2021-08-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
