# Generated by Django 3.2.6 on 2021-08-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20210816_0653'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='song',
            managers=[
            ],
        ),
    ]
