# Generated by Django 3.2.6 on 2021-08-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='songs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyric', to='polls.song'),
        ),
    ]
