# Generated by Django 3.2.6 on 2021-08-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_userstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='user',
            new_name='users',
        ),
    ]
