# Generated by Django 3.2.6 on 2021-08-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_product_super_marts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orders',
            new_name='customers',
        ),
    ]
