# Generated by Django 3.2.6 on 2021-08-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20210820_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
