# Generated by Django 3.2.6 on 2021-08-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_alter_productversion_weight'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supermart',
            index=models.Index(fields=['name'], name='shopping_su_name_95482d_idx'),
        ),
    ]
